export default [
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'za.jpg',
    LenguageText: 'ड',
    Sound: 'za.mp3',
    Title: '',
    _id: 26,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zb.jpg',
    LenguageText: 'ढ',
    Sound: 'zb.mp3',
    Title: '',
    _id: 27,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zc.jpg',
    LenguageText: 'ण',
    Sound: 'zc.mp3',
    Title: '',
    _id: 28,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zd.jpg',
    LenguageText: 'त',
    Sound: 'zd.mp3',
    Title: '',
    _id: 29,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'ze.jpg',
    LenguageText: 'थ',
    Sound: 'ze.mp3',
    Title: '',
    _id: 30,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zf.jpg',
    LenguageText: 'द',
    Sound: 'zf.mp3',
    Title: '',
    _id: 31,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zg.jpg',
    LenguageText: 'ध',
    Sound: 'zg.mp3',
    Title: '',
    _id: 32,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zh.jpg',
    LenguageText: 'न',
    Sound: 'zh.mp3',
    Title: '',
    _id: 33,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zi.jpg',
    LenguageText: 'प',
    Sound: 'zi.mp3',
    Title: '',
    _id: 34,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zj.jpg',
    LenguageText: 'फ',
    Sound: 'zj.mp3',
    Title: '',
    _id: 35,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zk.jpg',
    LenguageText: 'ब',
    Sound: 'zk.mp3',
    Title: '',
    _id: 36,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zl.jpg',
    LenguageText: 'भ',
    Sound: 'zl.mp3',
    Title: '',
    _id: 37,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'a.jpg',
    LenguageText: 'अ',
    Sound: 'a.mp3',
    Title: '',
    _id: 1,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'b.jpg',
    LenguageText: 'आ',
    Sound: 'b.mp3',
    Title: '',
    _id: 2,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'c.jpg',
    LenguageText: 'इ',
    Sound: 'c.mp3',
    Title: '',
    _id: 3,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'd.jpg',
    LenguageText: 'ई',
    Sound: 'd.mp3',
    Title: '',
    _id: 4,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'e.jpg',
    LenguageText: 'उ',
    Sound: 'e.mp3',
    Title: '',
    _id: 5,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'f.jpg',
    LenguageText: 'ऊ',
    Sound: 'f.mp3',
    Title: '',
    _id: 6,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'g.jpg',
    LenguageText: 'ऋ',
    Sound: 'g.mp3',
    Title: '',
    _id: 7,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'h.jpg',
    LenguageText: 'ए',
    Sound: 'h.mp3',
    Title: '',
    _id: 8,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'i.jpg',
    LenguageText: 'ऐ',
    Sound: 'i.mp3',
    Title: '',
    _id: 9,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'j.jpg',
    LenguageText: 'ओ',
    Sound: 'j.mp3',
    Title: '',
    _id: 10,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'k.jpg',
    LenguageText: 'औ',
    Sound: 'k.mp3',
    Title: '',
    _id: 11,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'l.jpg',
    LenguageText: 'अं',
    Sound: 'l.mp3',
    Title: '',
    _id: 12,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'm.jpg',
    LenguageText: 'अः',
    Sound: 'm.mp3',
    Title: '',
    _id: 13,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'n.jpg',
    LenguageText: 'क',
    Sound: 'n.mp3',
    Title: '',
    _id: 14,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'o.jpg',
    LenguageText: 'ख',
    Sound: 'o.mp3',
    Title: '',
    _id: 15,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'p.jpg',
    LenguageText: 'ग',
    Sound: 'p.mp3',
    Title: '',
    _id: 16,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'q.jpg',
    LenguageText: 'घ',
    Sound: 'q.mp3',
    Title: '',
    _id: 17,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 's.jpg',
    LenguageText: 'च',
    Sound: 's.mp3',
    Title: '',
    _id: 19,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 't.jpg',
    LenguageText: 'छ',
    Sound: 't.mp3',
    Title: '',
    _id: 20,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'u.jpg',
    LenguageText: 'ज',
    Sound: 'u.mp3',
    Title: '',
    _id: 21,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'v.jpg',
    LenguageText: 'झ',
    Sound: 'v.mp3',
    Title: '',
    _id: 22,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zm.jpg',
    LenguageText: 'म',
    Sound: 'zm.mp3',
    Title: '',
    _id: 38,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'y.jpg',
    LenguageText: 'ट',
    Sound: 'y.mp3',
    Title: '',
    _id: 24,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'z.jpg',
    LenguageText: 'ठ',
    Sound: 'z.mp3',
    Title: '',
    _id: 25,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zn.jpg',
    LenguageText: 'य',
    Sound: 'zn.mp3',
    Title: '',
    _id: 39,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zo.jpg',
    LenguageText: 'र',
    Sound: 'zo.mp3',
    Title: '',
    _id: 40,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zp.jpg',
    LenguageText: 'ल',
    Sound: 'zp.mp3',
    Title: '',
    _id: 41,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zq.jpg',
    LenguageText: 'व',
    Sound: 'zq.mp3',
    Title: '',
    _id: 42,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zr.jpg',
    LenguageText: 'श',
    Sound: 'zr.mp3',
    Title: '',
    _id: 43,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zs.jpg',
    LenguageText: 'ष',
    Sound: 'zs.mp3',
    Title: '',
    _id: 44,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zt.jpg',
    LenguageText: 'स',
    Sound: 'zt.mp3',
    Title: '',
    _id: 45,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zu.jpg',
    LenguageText: 'ह',
    Sound: 'zu.mp3',
    Title: '',
    _id: 46,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zv.jpg',
    LenguageText: 'क्ष',
    Sound: 'zv.mp3',
    Title: '',
    _id: 47,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zw.jpg',
    LenguageText: 'त्र',
    Sound: 'zw.mp3',
    Title: '',
    _id: 48,
  },
  {
    ActualSound: '',
    Category: 'Alphabet',
    Image: 'zx.jpg',
    LenguageText: 'ज्ञ',
    Sound: 'zx.mp3',
    Title: '',
    _id: 49,
  },
  //   {
  //     ActualSound: '',
  //     Category: 'Alphabet',
  //     Image: 'ang.png',
  //     LenguageText: 'ड़',
  //     Sound: ' ',
  //     Title: '',
  //     _id: 18,
  //   },
  //   {
  //     ActualSound: '',
  //     Category: 'Alphabet',
  //     Image: 'enya.png',
  //     LenguageText: 'ञ',
  //     Sound: 'zx.mp3',
  //     Title: '',
  //     _id: 23,
  //   },
];
export const data2 = [
  'अ',
  'आ',
  'इ',
  'ई',
  'उ',
  'ऊ',
  'ऋ',
  'ए',
  'ऐ',
  'ओ',
  'औ',
  'अं',
  'अः',
  'क',
  'ख',
  'ग',
  'घ',
  'ड़',
  'च',
  'छ',
  'ज',
  'झ',
  'ञ',
  'ट',
  'ठ',
  'ड',
  'ढ',
  'ण',
  'त',
  'थ',
  'द',
  'ध',
  'न',
  'प',
  'फ',
  'ब',
  'भ',
  'म',
  'य',
  'र',
  'ल',
  'व',
  'श',
  'ष',
  'स',
  'ह',
  'क्ष',
  'त्र',
  'ज्ञ',
];
